import urllib.request
import json
import os
import logging
from datetime import datetime
from typing import Optional, List, Dict

logger = logging.getLogger("GeminiService")

def call_gemini_optimizer(
    employees_data: List[Dict],
    shifts_data: List[Dict],
    leaves_data: List[Dict],
    current_assignments: List[Dict]
) -> Optional[List[Dict]]:
    """
    Sends the generated schedule and current database context to Gemini 2.5 Flash
    for optimization suggestions. Returns suggested changes or None if optimization failed.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        logger.warning("GEMINI_API_KEY is not set. Skipping Gemini optimization layer.")
        return None

    # Construct the prompt
    prompt = f"""
You are an expert AI Scheduler Optimizer.
We have an existing schedule generated by our rule-based system.
Your task is to analyze this schedule and suggest optimizations (e.g. shift swaps, better coverage, load balancing, or resolving shortages) while keeping as much of the existing assignments as possible.

EMPLOYEES:
{json.dumps(employees_data, indent=2)}

SHIFTS:
{json.dumps(shifts_data, indent=2)}

LEAVES FOR TODAY:
{json.dumps(leaves_data, indent=2)}

CURRENT PROPOSED ASSIGNMENTS:
{json.dumps(current_assignments, indent=2)}

Analyze this data and return optimized assignment suggestions in JSON format.
You must output a JSON object matching this schema:
{{
  "assignments": [
    {{
      "employee_id": <int>,
      "shift_id": <int>,
      "reason": "<string explanation of optimization>"
    }}
  ]
}}

Only include optimization suggestions where changes actually improve the schedule (e.g., workload balancing, department coverage, preferred shifts match). If the current schedule is optimal, you can return the current assignments or an empty list.
"""

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"
    payload = {
        "contents": [
            {
                "parts": [
                    {
                        "text": prompt
                    }
                ]
            }
        ],
        "generationConfig": {
            "responseMimeType": "application/json"
        }
    }

    # Prepare log folder and file path
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    log_dir = os.path.join(base_dir, "logs")
    os.makedirs(log_dir, exist_ok=True)
    log_file = os.path.join(log_dir, "gemini_api.log")

    # Log request
    try:
        with open(log_file, "a", encoding="utf-8") as f:
            f.write(f"\n--- REQUEST {datetime.now().isoformat()} ---\n")
            f.write(json.dumps(payload, indent=2))
    except Exception as le:
        logger.error(f"Failed to write to gemini_api.log: {le}")

    try:
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=20) as response:
            res_body = json.loads(response.read().decode("utf-8"))
            
            # Log response
            try:
                with open(log_file, "a", encoding="utf-8") as f:
                    f.write(f"\n--- RESPONSE {datetime.now().isoformat()} ---\n")
                    f.write(json.dumps(res_body, indent=2))
            except Exception as le:
                logger.error(f"Failed to write response to gemini_api.log: {le}")

            # Extract content text
            candidates = res_body.get("candidates", [])
            if not candidates:
                logger.warning("Gemini response returned no candidates.")
                return None
            content = candidates[0].get("content", {})
            parts = content.get("parts", [])
            if not parts:
                logger.warning("Gemini response returned no content parts.")
                return None
            text = parts[0].get("text", "")
            
            parsed_res = json.loads(text)
            return parsed_res.get("assignments")
    except Exception as e:
        logger.error(f"Error calling Gemini API: {e}")
        try:
            with open(log_file, "a", encoding="utf-8") as f:
                f.write(f"\n--- ERROR {datetime.now().isoformat()} ---\n")
                f.write(str(e))
        except Exception:
            pass
        return None
